### ISSUE TITLE
Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".

### ISSUE THREAD

**Issue by avongluck-r1soft** [codekitchen/ruby-protocol-buffers#42]
Seems like google protocol buffers have moved on to proto3.

**Comment by codekitchen** [comment]
There's a note in the README about proto3 https://github.com/codekitchen/ruby-protocol-buffers#protocol-buffers-v3

Can you give more details? Repro steps?

**Comment by codekitchen** [comment]
I'm closing this because of the README comment and because of inactivity
